### ISSUE TITLE
Using Mac with retina display

### ISSUE THREAD

**Issue by gregoryduckworth** [Crunch-io/nightwatch-vrt#18]
When taking a screenshot on a Mac with a retina display, it appears the resulting image which is cropped does not take into account the pixel density and so ends up with an image that is half the size of what it should be.

I've been using something similar to, however only works on newer browsers.
```
/*
 * Here we get the pixel density of the window and 
 * ensure that we adjust the width and height accordingly
 */
api.execute(function () {
  return window.devicePixelRatio;
}, [], function (result) {
  if (result.value > 1) {
    width = width * result.value;
    height = height * result.value;
  }
});
```

**Comment by kimulus** [comment]
I confirm this bug too on Mac Retina.

**Comment by digitalresistor** [comment]
We are currently running night watch in a Docker container and not hitting this issue at Crunch, if you could create a PR to fix this, we will be more than happy to accept it.

**Comment by gregoryduckworth** [comment]
I've raised #20 to hopefully address this, comments welcome.

**Comment by aberonni** [comment]
FWIW I think I have found a workaround. You can force `devicePixelRatio` to 1 by using chromeOptions. For example:

```js
chromeOptions = {
  mobileEmulation: {
    deviceMetrics: {
        touch: false,
        pixelRatio: 1
    }
  }
};
```

**Comment by digitalresistor** [comment]
I've merged this change into master. I will poke the right people internally to get a new package published to NPM (or at least get that power and do it myself).

**Comment by aberonni** [comment]
Thanks @bertjwregeer !
